---
- import_playbook: ../default/converge.yml

- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create cnvrg spec
      k8s:
        state: "present"
        wait: "yes"
        definition:
          apiVersion: mlops.cnvrg.io/v1
          kind: CnvrgApp
          metadata:
            name: cnvrg-app
            namespace: cnvrg
          spec:
            clusterDomain: "taint.azops.cnvrg.io"
            tenancy:
              enabled: "true"
            ingressType: "k8singress"
            cnvrgApp:
              intercom: "false"
