---
dependency:
  name: galaxy
driver:
  name: delegated
#lint: |
  #set -e
  #yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    verify: ./verify.yml
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: "cnvrg"
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        project_dir: ${MOLECULE_PROJECT_DIRECTORY}
        operator_image: ${OPERATOR_IMAGE:-""}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/.kube/config"}
    ANSIBLE_STDOUT_CALLBACK: debug
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
